# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.models.agent_create_public import AgentCreatePublic


class TestAgentCreatePublic(unittest.TestCase):
    """AgentCreatePublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentCreatePublic:
        """Test AgentCreatePublic
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AgentCreatePublic`
        """
        model = AgentCreatePublic()
        if include_optional:
            return AgentCreatePublic(
                name = '',
                description = '',
                model = 'anthropic_claude_3_5_sonnet_v1',
                custom_prompt = '',
                allowed_tools = [
                    ''
                    ],
                use_mcp = True,
                mcp_server_urls = [
                    ''
                    ],
                agent_strategy = 'react',
                stream = True,
                active = True
            )
        else:
            return AgentCreatePublic(
                name = '',
        )
        """

    def testAgentCreatePublic(self):
        """Test AgentCreatePublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
