# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.models.crawler_job_status_response import CrawlerJobStatusResponse

class TestCrawlerJobStatusResponse(unittest.TestCase):
    """CrawlerJobStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrawlerJobStatusResponse:
        """Test CrawlerJobStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrawlerJobStatusResponse`
        """
        model = CrawlerJobStatusResponse()
        if include_optional:
            return CrawlerJobStatusResponse(
                job_id = '',
                status = 'pending',
                progress = 56,
                error = '',
                result_url = '',
                organisation = '',
                user_id = '',
                submitted_at = '',
                updated_at = ''
            )
        else:
            return CrawlerJobStatusResponse(
                job_id = '',
                status = 'pending',
                progress = 56,
                error = '',
                result_url = '',
                organisation = '',
                user_id = '',
                submitted_at = '',
                updated_at = '',
        )
        """

    def testCrawlerJobStatusResponse(self):
        """Test CrawlerJobStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
