# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.api.completions_api import CompletionsApi


class TestCompletionsApi(unittest.TestCase):
    """CompletionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompletionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_chat_completion_rag_generation_chat_completions_post(self) -> None:
        """Test case for create_chat_completion_rag_generation_chat_completions_post

        chat completions
        """
        pass


if __name__ == "__main__":
    unittest.main()
