# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.api.models_api import ModelsApi


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelsApi()

    def tearDown(self) -> None:
        pass

    def test_list_models_rag_generation_models_get(self) -> None:
        """Test case for list_models_rag_generation_models_get

        List Models
        """
        pass


if __name__ == "__main__":
    unittest.main()
