# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.api.file_management_api import FileManagementApi


class TestFileManagementApi(unittest.TestCase):
    """FileManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileManagementApi()

    def tearDown(self) -> None:
        pass

    def test_delete_files_fileman_data_delete_delete(self) -> None:
        """Test case for delete_files_fileman_data_delete_delete

        delete files
        """
        pass

    def test_list_files_get_fileman_data_list_get(self) -> None:
        """Test case for list_files_get_fileman_data_list_get

        list files (GET method)
        """
        pass

    def test_upload_file_fileman_data_upload_post(self) -> None:
        """Test case for upload_file_fileman_data_upload_post

        upload files
        """
        pass


if __name__ == "__main__":
    unittest.main()
