# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.models.chat_completion_request_public import (
    ChatCompletionRequestPublic,
)


class TestChatCompletionRequestPublic(unittest.TestCase):
    """ChatCompletionRequestPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionRequestPublic:
        """Test ChatCompletionRequestPublic
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ChatCompletionRequestPublic`
        """
        model = ChatCompletionRequestPublic()
        if include_optional:
            return ChatCompletionRequestPublic(
                data_type = '',
                agent_flag = True,
                agent_name = '',
                agent_strategy = '',
                agent_history_enabled = True,
                model = '',
                knowledge_base = '',
                messages = [
                    verity_ai_pyc.models.message.Message(
                        role = '', 
                        content = '', )
                    ],
                database_name = '',
                table_name = '',
                stream = True,
                max_trials = 56
            )
        else:
            return ChatCompletionRequestPublic(
                messages = [
                    verity_ai_pyc.models.message.Message(
                        role = '', 
                        content = '', )
                    ],
        )
        """

    def testChatCompletionRequestPublic(self):
        """Test ChatCompletionRequestPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
