# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verity_ai_pyc.models.knowledge_base2 import KnowledgeBase2

class TestKnowledgeBase2(unittest.TestCase):
    """KnowledgeBase2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeBase2:
        """Test KnowledgeBase2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeBase2`
        """
        model = KnowledgeBase2()
        if include_optional:
            return KnowledgeBase2(
            )
        else:
            return KnowledgeBase2(
        )
        """

    def testKnowledgeBase2(self):
        """Test KnowledgeBase2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
