# coding: utf-8

"""
    AI Labs API Service

    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "Verity AI Python Client"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="AI Labs API Service",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://github.com/veritylabs/verity-ai-python-client",
    keywords=["OpenAPI", "OpenAPI-Generator", "AI Labs API Service"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type="text/markdown",
    long_description="""\
    Comprehensive API service for unstructured and structured RAG generation, file management, UI interactions, ground truth generation, and evaluation
    """,  # noqa: E501
    package_data={"verity_ai_pyc": ["py.typed"]},
)
